import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // CareerForge AI design system
        primary: "#006b54",
        secondary: "#266956",
        tertiary: "#aa324b",
        surface: "#f2fcf5",
        background: "#f2fcf5",
        error: "#ba1a1a",
        outline: "#6a7b73",
        "surface-tint": "#006b54",
        "secondary-container": "#aaeed4",
        "surface-variant": "#dbe5df",
        "primary-fixed-dim": "#00e0b2",
        "primary-container": "#00ffcb",
        "surface-container-high": "#e1ebe4",
        "tertiary-container": "#ffd9dc",
        "on-primary-fixed": "#002118",
        "on-primary-fixed-variant": "#00513f",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffd9dc",
        "surface-container-low": "#ecf6f0",
        "on-error-container": "#93000a",
        "on-surface-variant": "#3a4a44",
        "inverse-primary": "#00e0b2",
        "on-secondary-fixed": "#002118",
        "on-tertiary-container": "#b13751",
        "on-error": "#ffffff",
        "on-secondary-container": "#2b6e5a",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#891835",
        "tertiary-fixed-dim": "#ffb2bb",
        "outline-variant": "#b9cbc2",
        "inverse-surface": "#29322e",
        "on-surface": "#151d1a",
        "primary-fixed": "#26ffcc",
        "surface-container-highest": "#dbe5df",
        "surface-container": "#e6f0ea",
        "on-tertiary-fixed": "#400011",
        "surface-bright": "#f2fcf5",
        "inverse-on-surface": "#e9f3ed",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#acf0d7",
        "on-background": "#151d1a",
        "on-primary-container": "#007259",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#00513f",
        "secondary-fixed-dim": "#91d4bc",
        "surface-dim": "#d2dcd6",
        // Legacy brand colors retained for backward compatibility
        brand: {
          50: "#eef4ff",
          100: "#d9e6ff",
          400: "#6c8dff",
          500: "#3b62ff",
          600: "#2745d6",
          700: "#1f37a8",
          900: "#101a4f",
        },
        ink: { 900: "#0a0d1f", 800: "#101635", 700: "#1a2147" },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "0.5rem",
        sm: "1rem",
        md: "1.5rem",
        lg: "2.5rem",
        xl: "4rem",
        gutter: "1.5rem",
        margin: "2rem",
        base: "0.25rem",
      },
      fontFamily: {
        sans: ["var(--font-hanken)", "Hanken Grotesk", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "body-md": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "body-lg": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "headline-lg": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "headline-md": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "label-md": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "label-sm": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "display-lg": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        display: ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        headline: ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        body: ["var(--font-mono)", "JetBrains Mono", "monospace"],
        label: ["var(--font-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      backgroundImage: {
        "grid-fade": "radial-gradient(ellipse at top, rgba(0,107,84,0.08), transparent 60%)",
        "hero-gradient":
          "radial-gradient(circle at top right, rgba(0,107,84,0.05), transparent), radial-gradient(circle at bottom left, rgba(38,105,86,0.03), transparent)",
      },
    },
  },
  // @ts-ignore
  plugins: [require("@tailwindcss/typography")],
};
export default config;
